### ISSUE TITLE
error: Something is calling a React component directly. Use a factory or JSX instead

### ISSUE THREAD

**Issue by avieln** [cupcake/react-modal#3]
Hey! 
thanks for sharing this!~
i am having 2 issues with requiring the modal through browserify, after npm install.

1. seems like the require 'React' inside of the modal.js should be requre 'react' since 'React' is not found.
2. i get this error when i try to render a modal like this:

      return (
          <div>
            <button onClick={this.openModal}>Open Modal</button>
            <Modal
              visible='true'>
          
            </Modal>
          </div>
        );

and the error:

Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
bundle.js:18510 Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
bundle.js:38423 Warning: Modal(...): No `render` method found on the returned component instance: you may have forgotten to define `render` in your component or you may have accidentally tried to render an element whose type is a function that isn't a React component.
bundle.js:18510 Warning: Don't set the props property of the component. Mutate the existing props object instead.
bundle.js:25129 Uncaught TypeError: Can't add property context, object is not extensible

any idea what might solve this?

**Comment by jvatic** [comment]
What version of React are you using?

**Comment by jvatic** [comment]
I should note that this hasn't been tested using an npm workflow. Can you provide a gist reproducing this issue?

**Comment by avieln** [comment]
hey, this is react 0.13 that produce this error, not sure what you mean about gist though

**Comment by jvatic** [comment]
This hasn't been updated for 0.13 yet, though none of the [breaking changes](https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html) should effect it. By [gist](https://gist.github.com) I mean a minimal sample project which produces the same error.

**Comment by avieln** [comment]
hey Jesse,
this is what cause me erros:
https://gist.github.com/88135ca3bc4e7708adfd.git

**Comment by jvatic** [comment]
It appears to be an issue with the React code being included as the same example using the same version of React (0.13.1) from the [CDN](https://cdnjs.com/libraries/react/) works: https://gist.github.com/jvatic/78055fddf6f85bebdda7.
