### ISSUE TITLE
Body overflow hidden not being cleared on IE11

### ISSUE THREAD

**Issue by davidxmoody** [cupcake/react-modal#4]
Hi, 

Thank you for releasing this plugin, I've found it pretty useful.

One issue I've ran into is that on Internet Explorer 11 (and maybe other browsers), the overflow:hidden inline style on the body element is not being cleared when the modal is closed. 

Line 74 appears to be causing the issue:

```js
document.body.style.overflow = null;
```

Changing it to the following should work I think:

```js
document.body.style.overflow = '';
```

Sorry I don't have time to fix it and test it properly right now. I can submit a pull request later if you would like.

**Comment by jvatic** [comment]
@davidxmoody Thanks for reporting this!
